---
- name: Gather Docker Containers Info
  hosts: all
  gather_facts: false

  tasks:
  - name: Get Docker Containers Info
    community.docker.docker_container_info:
      containers: []
    register: containers_info

  - name: Get Docker Images Info
    community.docker.docker_image_info:
      images: []
    register: images_info

  - name: Get Docker Networks Info
    community.docker.docker_network_info:
      networks: []
    register: networks_info
