---
- name: Get Docker Information
  hosts: all
  gather_facts: false

  tasks:
    - name: Get all Docker containers with names, status, and ports
      shell: docker ps -a --format "{{ '{{' }}.Names{{ '}}' }} - {{ '{{' }}.Status{{ '}}' }} - {{ '{{' }}.Ports{{ '}}' }}"
      register: docker_containers

   # - name: Print all Docker containers with names, status, and ports
   #   debug:
   #     msg: "{{ docker_containers.stdout_lines }}"

    - name: Get all Docker images
      shell: docker images --format "{{ '{{' }}.Repository{{ '}}' }}:{{ '{{' }}.Tag{{ '}}' }}"
      register: docker_images

   # - name: Print all Docker images
   #   debug:
   #     msg: "{{ docker_images.stdout_lines }}"
