---
- name: Get logs of a specific Docker container
  hosts: all
  gather_facts: false

  tasks:
  
  - name: Get container logs
    command: "docker logs {{ container_name }}"
    register: container_logs  # Capture the output of the log command

  - name: Display container logs
    debug:
      var: container_logs.stdout_lines  # Display the captured output
