---
- name: Get Docker Information
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get all Docker container names
      command: 'docker ps -a --format "{{.Names}}"'
      register: docker_containers

    - name: Print all Docker container names
      debug:
        msg: "{{ docker_containers.stdout_lines }}"

    - name: Get all Docker images
      command: 'docker images --format "{{.Repository}}:{{.Tag}}"'
      register: docker_images

    - name: Print all Docker images
      debug:
        msg: "{{ docker_images.stdout_lines }}"

    - name: Get all Docker networks
      command: 'docker network ls --format "{{.Name}}"'
      register: docker_networks

    - name: Print all Docker networks
      debug:
        msg: "{{ docker_networks.stdout_lines }}"
